### ISSUE TITLE
Untuk B1 kacau hasilnya?

### ISSUE THREAD

**Issue by banghasan** [bachors/TagihanPLN.php#1]
Coba id pelanggannya dimasukkan ini : 538712131164

Hasil:

> {
>     "status": "success",
>     "query": {
>         "id_pelanggan": "538712131164",
>         "tahun": "2016",
>         "bulan": "06"
>     },
>     "data": {
>         "diskon": "0",
>         "angsuran": "ppn",
>         "thblrek": "201606",
>         "slakvarh": "invoice",
>         "lwbp": "786500",
>         "fkt": " ",
>         "fakmkvarh": "beban",
>         "sahwbp": "sahkvarh",
>         "fakmkvam": "fakm",
>         "1": "bpju",
>         "39325": "ptl",
>         "idpel": "538712131164",
>         "sahlwbp": "475530000",
>         "tglbacalalu": "26-04-2016",
>         "slawbp": "sewa",
>         "nama": "ZAMRI ZAMTHA BE",
>         "namaupi": "JAWA BARAT",
>         "daya": "4400",
>         "fjn": "N",
>         "jamnyala": "mat",
>         "3000": "slalwbp",
>         "468380000": "pemkwh",
>         "715": "tagihan",
>         "828825": "namathblrek",
>         "Juni 2016": "terbilang",
>         "Delapan Ratus Dua Puluh Delapan Ribu Delapan Ratus Dua Puluh Lima Rupiah ": "wbp",
>         "kvarh": "alamat",
>         "JL MARGONDA No.1 RT.000 RW.00 BEJI ": "tglbacaakhir",
>         "27-05-2016": "tarif",
>         "B1": null
>     }

**Comment by bachors** [comment]
Terimakasih mas @banghasan  :+1:  sekarang sudah fix silahkan di coba lagi :)
